version: 2
jobs:
  build-publish:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Clone all repos, build then, test them
          command: ./sh/git-clone-all.sh

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
